#Pertemuan 5

##Library

In [ ]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.cluster import AgglomerativeClustering
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.cluster import adjusted_rand_score
from sklearn.metrics.cluster import fowlkes_mallows_score

#Latihan 1

##Dataset

In [ ]:
# data tabular
df = pd.DataFrame(
    {
        "ID Buah": pd.Series([1,2,3,4,5]),
        "Diameter": pd.Series([7.0,7.1,6.5,6.6,6.8]),
        "Berat": pd.Series([165,170,180,195,200])
    }
)

##Pre-processing

In [ ]:
# pemilihan feature
X = df.drop("ID Buah", axis=1)
X

   Diameter  Berat
0       7.0    165
1       7.1    170
2       6.5    180
3       6.6    195
4       6.8    200

##Modeling menggunakan Agglomerative Clustering

In [ ]:
clustering = AgglomerativeClustering().fit(X)
df["cluster"] = clustering.labels_
df

   ID Buah  Diameter  Berat  cluster
0        1       7.0    165        0
1        2       7.1    170        0
2        3       6.5    180        0
3        4       6.6    195        1
4        5       6.8    200        1

#Latihan2

In [ ]:
df_raw = pd.read_csv("https://raw.githubusercontent.com/rahmantaufik27/dataset/main/study/student_score_pass.csv")
df_raw

,npm,activeness_score,assignment_score,pre_test_score,post_test_score,midterm_test_score,end_semester_test_score,pass_test
0,2022041101,99,71.0,93.0,52.0,44.0,24,not pass
1,2022041102,96,77.0,NaN,27.0,100.0,89,pass
2,2022041103,86,71.0,84.0,17.0,21.0,41,not pass
3,2022041104,81,96.0,NaN,NaN,11.0,99,not pass
4,2022041105,93,85.0,68.0,29.0,44.0,50,not pass
...,...,...,...,...,...,...,...,...
367,2022041468,91,NaN,31.0,52.0,31.0,46,not pass
368,2022041469,96,87.0,55.0,56.0,95.0,11,pass
369,2022041470,569,83.0,89.0,15.0,86.0,13,not pass
370,2022041471,84,92.0,87.0,97.0,42.0,27,pass
371,2022041472,90,99.0,96.0,60.0,82.0,65,not pass

Preprocessing

In [ ]:
# feature selection
x = [0 if x == 'not pass' else 1 for x in df_raw.dropna()['pass_test']]
df_training = df_raw.drop(['npm', 'pass_test'], axis = 1)
# hapus NaN
df_training = df_training.dropna()
df_training

,activeness_score,assignment_score,pre_test_score,post_test_score,midterm_test_score,end_semester_test_score
0,99,71.0,93.0,52.0,44.0,24
2,86,71.0,84.0,17.0,21.0,41
4,93,85.0,68.0,29.0,44.0,50
5,85,95.0,34.0,73.0,57.0,98
6,95,79.0,52.0,54.0,85.0,13
...,...,...,...,...,...,...
366,88,75.0,80.0,11.0,55.0,82
368,96,87.0,55.0,56.0,95.0,11
369,569,83.0,89.0,15.0,86.0,13
370,84,92.0,87.0,97.0,42.0,27
371,90,99.0,96.0,60.0,82.0,65

Modeling

In [ ]:
model = AgglomerativeClustering().fit(df_training)
# hasil clustering
df_training["kluster"] = model.labels_
df_training

,activeness_score,assignment_score,pre_test_score,post_test_score,midterm_test_score,end_semester_test_score,kluster
0,99,71.0,93.0,52.0,44.0,24,0
2,86,71.0,84.0,17.0,21.0,41,0
4,93,85.0,68.0,29.0,44.0,50,0
5,85,95.0,34.0,73.0,57.0,98,0
6,95,79.0,52.0,54.0,85.0,13,0
...,...,...,...,...,...,...,...
366,88,75.0,80.0,11.0,55.0,82,0
368,96,87.0,55.0,56.0,95.0,11,0
369,569,83.0,89.0,15.0,86.0,13,1
370,84,92.0,87.0,97.0,42.0,27,0
371,90,99.0,96.0,60.0,82.0,65,0

In [ ]:
len(df_training["kluster"].unique())

2

#Tugas

evaluasi model algoritma agglomerative clustering dari data latihan 2 dengan mencari nilai akurasinya
Hint: splitting data, modeling, accuracy store

In [ ]:
scaler = StandardScaler()
train_scaled = scaler.fit_transform(df_training)
agglomerative = AgglomerativeClustering(n_clusters = 2)
agglomerative.fit(train_scaled)

AgglomerativeClustering()

In [ ]:
print(agglomerative.labels_)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0]

In [ ]:
# kolom cluster
df_training['cluster'] = agglomerative.labels_

# kolom pass
df_training['pass'] = x
df_training

,activeness_score,assignment_score,pre_test_score,post_test_score,midterm_test_score,end_semester_test_score,kluster,pass,cluster
0,99,71.0,93.0,52.0,44.0,24,0,0,0
2,86,71.0,84.0,17.0,21.0,41,0,0,0
4,93,85.0,68.0,29.0,44.0,50,0,0,0
5,85,95.0,34.0,73.0,57.0,98,0,0,0
6,95,79.0,52.0,54.0,85.0,13,0,0,0
...,...,...,...,...,...,...,...,...,...
366,88,75.0,80.0,11.0,55.0,82,0,0,0
368,96,87.0,55.0,56.0,95.0,11,0,1,0
369,569,83.0,89.0,15.0,86.0,13,1,0,1
370,84,92.0,87.0,97.0,42.0,27,0,1,0
371,90,99.0,96.0,60.0,82.0,65,0,0,0

In [ ]:
adjusted_rand_score(agglomerative.labels_, x)

0.0018051839508165203

In [ ]:
fowlkes_mallows_score(agglomerative.labels_, x)

0.7259983309240835